version: "3.8"
services:
  database_container:
    build: ./database_container/
  flask_container:
    build: ./flask_container/
    ports:
      - "80:5000"
    depends_on:
      - database_container
