services:
  database_container:
    build: ./database_container/
    ports:
      - "5432:5432"
  flask_container:
    build: ./flask_container/
    ports:
      - "80:5000"
    depends_on:
      - database_container
