version: "3.8"
services:
  database_container:
    build: ./database_container/
  flask_container:
    build: ./flask_container/
    ports:
      - "5000:5000"
    depends_on:
      - database_container
  nginx_proxy:
    build: ./nginx_proxy/
    ports:
      - 8080:80
    depends_on:
      - flask_container